### ISSUE TITLE
有Typora的接口开发文档不?

### ISSUE THREAD

**Issue by carve-myself** [typora-community-plugin/typora-community-plugin#1]

**Comment by plylrnsdy** [comment]
官方没有开放接口，完整文档是没有的。

我在 Devtools 调试得到部分接口 [packages/types/index.d.ts](https://github.com/typora-community-plugin/typora-community-plugin/blob/main/packages/types/index.d.ts)，如果缺少接口也欢迎 pr

可以通过 npm 安装：
```sh
$ npm i -D @typora-community-plugin/typora-types
```

由于是私有接口，所以不同 Typora 版本可能有所不同
