### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by WMD001** [typora-community-plugin/typora-community-plugin#12]
## 1.插件市场下载安装失败
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/35905864/03afdeb6-8f3c-4c7d-aed1-79db54fa8f2c)

```
EXDEV: cross-device link not permitted, rename 'C:\Users\habit\AppData\Roaming\Typora\plugins\_temp\3' -> 'D:\software\Typora\.typora\plugins\typora-community-plugin.tag'
```

## 2.手动把插件放入plugins目录后启动加载插件失败
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/35905864/21bd438c-421e-46fa-afed-4904253242c9)

**Comment by plylrnsdy** [comment]
缺少信息，请问 C:\Users\habit\AppData\Roaming\Typora\plugins 这个“文件链接”创建成功了吗？

**Comment by WMD001** [comment]
在另一台电脑上重新安装了一下，插件还是不生效

安装过程
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/35905864/75d963ca-6246-4230-a191-de3c3a5a12a4)

文件链接
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/35905864/0722fe3b-58dd-4fdd-a831-5ef62327f486)

下载插件提示
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/35905864/8646bd48-df95-45d6-8e2c-d745f4fc2aae)

手动从_temp 文件夹复制到 typora 安装目录下的 `.typora/plugins` ，可以在已安装插件中看到
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/35905864/069d301f-3429-4913-9a51-ac31a6930c03)

语法未生效
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/35905864/76cc79e0-70d9-489f-bd74-c5533d750528)

**Comment by plylrnsdy** [comment]
你是怎么链接 .typora 到 D 盘的？我链接过去没问题啊

**Comment by WMD001** [comment]
没有链接到D盘，
是%APPDATA% 里边的 Typora/plugins 链接到了 用户目录下的 .typora

![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/35905864/3e9cf4a9-c9f6-4550-908d-39e8c9b061e3)


![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/35905864/fd4cecbb-81fb-4123-b115-6a5ce46757c7)

**Comment by plylrnsdy** [comment]
第一张图不是显示 D:\software\Typora\.typora\plugins\typora-community-plugin.tag 吗？

**Comment by WMD001** [comment]
这个我没有设置过，是在插件市场下载插件时候提示的错误异常

**Comment by plylrnsdy** [comment]
哦哦，你这个是因为笔记目录不在 C 盘，又想把插件装到笔记目录造成的，我修一修

**Comment by WMD001** [comment]
好的， 我试试

**Comment by WMD001** [comment]
另外，文档部分，可以增加一下手动安装插件的说明吗，还有就是在开发阶段如何调试插件

**Comment by plylrnsdy** [comment]
文档在这里

- [手动安装插件](https://github.com/typora-community-plugin/typora-community-plugin/blob/main/docs/zh-cn/user-guide/plugin-installation.md#%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85) `新增`
- [插件开发](https://github.com/typora-community-plugin/typora-community-plugin/blob/main/docs/zh-cn/dev-guide/1-getting-started.md#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)
