### ISSUE TITLE
求添加折叠代码块的插件 Plugin "Collapsible Section" support codeblock

### ISSUE THREAD

**Issue by WangChao2021** [typora-community-plugin/typora-community-plugin#13]
大佬，插件系统和内容折叠的插件很好用，代码折叠也添加一个呗，这个很需要。

**Comment by plylrnsdy** [comment]
我的想法是：

- 代码块右上角提供一个按钮，可以将超过3行的代码可折叠成3行
- 设置里可以提供“默认折叠所有代码块”选项

你还有想要补充的想法吗？

**Comment by WangChao2021** [comment]
> 我的想法是：
> 
> * 代码块右上角提供一个按钮，可以将高度大于 x 的代码折叠成高度等于 x
> * 设置里可以提供“默认折叠所有代码块”选项、“折叠高度”选项
> 
> 你还有想要补充的想法吗？

1. 代码折叠，我想要的就是折叠所有代码而不是 “折短”，我用语雀也比较多，语雀的代码折叠还比较好用，大佬可以参考下。
![recording](https://github.com/typora-community-plugin/typora-community-plugin/assets/95513088/6e5d0417-2c17-461c-b75b-f151fa290143)

2. 折叠高度，我个人觉得必要性没那么大，到是可以搞一个全局的设置，设置代码块的最大高度，超过了最大高度就默认通过滚动条进行查看，不需要单独触发。

3. 语雀也支持这种代码块的高度设置，它那个就更方便了，可以手动拖代码块的高度，Typora 这种应该没法实现针对文章级别的控制，能做到第2点就很好了。

再次感谢下作者提供了这样插件系统！！！

**Comment by plylrnsdy** [comment]
1. Typora 的代码块没有标题，折叠后只显示第一行的话会很奇怪；还是说显示空白的标题栏
2. 限制高度作为折叠的话，可以实现点击代码块展开到原高度
3. -

**Comment by plylrnsdy** [comment]
目前得效果是这样的：

![example](https://github.com/typora-community-plugin/typora-community-plugin/assets/18095255/18e0653c-a778-47a9-9afc-54ea05c69d35)

**Comment by WangChao2021** [comment]
> 目前的效果是这样的：
> 
> ![example](https://private-user-images.githubusercontent.com/18095255/331808575-18e0653c-a778-47a9-9afc-54ea05c69d35.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzUzOTgsIm5iZiI6MTcxNjA3NTA5OCwicGF0aCI6Ii8xODA5NTI1NS8zMzE4MDg1NzUtMThlMDY1M2MtYTc3OC00N2E5LTlhZmMtNTRlYTA1YzY5ZDM1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIzMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkM2RkMjYzMDBkOGRjZmRiYzQzMjk2ZjM4ZDlkMGJmMjVhYzYyMmIzMTc3ZjJjZmYxNzQ4NzdiY2Y3MmQ5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yw5XC2vDzZc-mFxrcRBe6bTl7AlfYXOKKF1w7dKkb54) [ ![example](https://private-user-images.githubusercontent.com/18095255/331808575-18e0653c-a778-47a9-9afc-54ea05c69d35.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzUzOTgsIm5iZiI6MTcxNjA3NTA5OCwicGF0aCI6Ii8xODA5NTI1NS8zMzE4MDg1NzUtMThlMDY1M2MtYTc3OC00N2E5LTlhZmMtNTRlYTA1YzY5ZDM1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIzMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkM2RkMjYzMDBkOGRjZmRiYzQzMjk2ZjM4ZDlkMGJmMjVhYzYyMmIzMTc3ZjJjZmYxNzQ4NzdiY2Y3MmQ5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yw5XC2vDzZc-mFxrcRBe6bTl7AlfYXOKKF1w7dKkb54) ](https://private-user-images.githubusercontent.com/18095255/331808575-18e0653c-a778-47a9-9afc-54ea05c69d35.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzUzOTgsIm5iZiI6MTcxNjA3NTA5OCwicGF0aCI6Ii8xODA5NTI1NS8zMzE4MDg1NzUtMThlMDY1M2MtYTc3OC00N2E5LTlhZmMtNTRlYTA1YzY5ZDM1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIzMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkM2RkMjYzMDBkOGRjZmRiYzQzMjk2ZjM4ZDlkMGJmMjVhYzYyMmIzMTc3ZjJjZmYxNzQ4NzdiY2Y3MmQ5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yw5XC2vDzZc-mFxrcRBe6bTl7AlfYXOKKF1w7dKkb54) [ ](https://private-user-images.githubusercontent.com/18095255/331808575-18e0653c-a778-47a9-9afc-54ea05c69d35.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzUzOTgsIm5iZiI6MTcxNjA3NTA5OCwicGF0aCI6Ii8xODA5NTI1NS8zMzE4MDg1NzUtMThlMDY1M2MtYTc3OC00N2E5LTlhZmMtNTRlYTA1YzY5ZDM1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIzMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkM2RkMjYzMDBkOGRjZmRiYzQzMjk2ZjM4ZDlkMGJmMjVhYzYyMmIzMTc3ZjJjZmYxNzQ4NzdiY2Y3MmQ5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yw5XC2vDzZc-mFxrcRBe6bTl7AlfYXOKKF1w7dKkb54)
> 
> ![setting](https://private-user-images.githubusercontent.com/18095255/331808918-2f2476d9-8541-43a3-b8be-a0b7b0b45971.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzUzOTgsIm5iZiI6MTcxNjA3NTA5OCwicGF0aCI6Ii8xODA5NTI1NS8zMzE4MDg5MTgtMmYyNDc2ZDktODU0MS00M2EzLWI4YmUtYTBiN2IwYjQ1OTcxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIzMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNzU1NjM3NTU2YWIzMTk1MmNjYTg2OGQzY2QwZDRmNjU4ODVhMjBkZTc5ZTRjOWE2NGI3ZmNiZjAwMDY2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2P1_ewuJsQ7nhMbGzdsLtLAAxnk0Pa3zcLQtNWe2ulU)
> 
> 如果觉得可以，我就发布

这样就很好了

**Comment by plylrnsdy** [comment]
[Collapsible Section](https://github.com/typora-community-plugin/typora-plugin-collapsible-section) 更新了 1.3.0

在“设置 -> 已安装插件”中使用“检查更新”按钮检查更新，再选择 Collapsible Section 的“更新”按钮更新
