### ISSUE TITLE
查看插件系统关于中的作者和项目主页，Typora 会闪退

### ISSUE THREAD

**Issue by WangChao2021** [typora-community-plugin/typora-community-plugin#14]
在插件系统的关于中，查看作者和项目主页等点击链接，Typora 都会闪退
![Clip_2024-05-20_10-46-23](https://github.com/typora-community-plugin/typora-community-plugin/assets/95513088/94ec621e-8958-4779-9605-1f8e9f48fe30)

Typora 版本：1.8.10
插件版本：v2.0.0-beta.36
windows 版本：win11专业版 22H2，操作系统版本号：22621.3447

**Comment by plylrnsdy** [comment]
已修复，与 v2.0.0-beta.37 中发布
