### ISSUE TITLE
当前标签优化建议

### ISSUE THREAD

**Issue by WangChao2021** [typora-community-plugin/typora-community-plugin#15]
插件能实现标签页确实很方便，不过目前的标签页样式确实不精致也不太好看

我自己基于官方的主题，调了一个css主题，也针对当前的标签页的样式进行了优化：
1. **调整标签页大小和样式，使其更精致**
2. **每个标签页添加一个文档的 logo**
3. **增加标签页的鼠标悬停效果**
4. **调整关闭按钮大小，间距，使其小页美**
5. **关闭按钮默认不显示，仅当前页默认显示，关闭按钮也支持悬停效果**
6. **只打开一个页签时，默认不显示页签**

当前标签页样式
![recording](https://github.com/typora-community-plugin/typora-community-plugin/assets/95513088/8cef5573-880f-45be-9414-dcf3531e7cbf)

CSS优化后的标签页样式
![recording](https://github.com/typora-community-plugin/typora-community-plugin/assets/95513088/ad7d9022-93cb-4ee8-b5a4-f422545073f9)

因为主题是基于官方的主题调的，完整的主题CSS不方便直接公开提供，如果需要，我可以单独提供css文件

**优化建议**：
1. 另外建议将标签页中文件名的".md"后缀去除，每个标签页都显示一个 ".md" 显得有点多余；
2. 希望能支持鼠标中键点击标签页关闭，和常规浏览器一样。

**Comment by plylrnsdy** [comment]
我是参考左边文件树的样式调的
- 和原有UI的文件树风格接近，不然不搭的话，可能多数人接受不了
- 兼容（不同主题的）主题色
- 兼容亮色和暗色主题

如果个人不喜欢，可以自己改样式（问作者喜不喜欢自己写的样式，通常都是喜欢的吧😂

文件名后缀的问题，我加个配置选项吧

**Comment by WangChao2021** [comment]
> 我是参考左边文件树的样式调的
> 
> * 和原有UI的文件树风格接近，不然不搭的话，可能多数人接受不了
> * 兼容（不同主题的）主题色
> * 兼容亮色和暗色主题
> 
> 如果个人不喜欢，可以自己改样式（问作者喜不喜欢自己写的样式，通常都是喜欢的吧😂
> 
> 文件名后缀的问题，我加个配置选项吧

嗯，说的也是，原来设计可以兼容不同的主题，文件名后缀那个可以加下配置开关

**Comment by WangChao2021** [comment]
> 我是参考左边文件树的样式调的
> 
> * 和原有UI的文件树风格接近，不然不搭的话，可能多数人接受不了
> * 兼容（不同主题的）主题色
> * 兼容亮色和暗色主题
> 
> 如果个人不喜欢，可以自己改样式（问作者喜不喜欢自己写的样式，通常都是喜欢的吧😂
> 
> 文件名后缀的问题，我加个配置选项吧

如果标签页能再支持鼠标中键关闭的功能，就更好了，这样就和浏览器的使用习惯保持一致。

**Comment by plylrnsdy** [comment]
更新在 2.0.8

- 隐藏文件名后缀，可以勾选 “插件设置 -> 外观 -> 高级选项 -> 隐藏文件标签的文件扩展名”
- 使用中键可以关闭标签
