### ISSUE TITLE
按照文档示例里面使用模板创建插件运行npm run build:dev后报错

### ISSUE THREAD

**Issue by missuor** [typora-community-plugin/typora-community-plugin#16]
$ npm install

up to date, audited 281 packages in 1s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm run build:dev

> build:dev
> node build.js

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Module.join (node:path:1171:7)
    at closeTypora (file:///home/huhai/codes/tools/typora/typora-markdown-linter/node_modules/esbuild-plugin-typora/index.js:1:2324)
    at file:///home/foo/codes/tools/typora/typora-markdown-linter/build.js:32:9 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.19.1

**Comment by plylrnsdy** [comment]
这是一个 pmpm 项目

- 使用 `npm install -g pnpm` 安装 pnpm
- (可选) 如果需要快捷更改源仓库（如淘宝镜像），可以安装 `pnpm install -g nrm`
- (可选) 切换源仓库到淘宝镜像 `nrm use taobao`
- 使用 `pnpm install` 安装重新依赖

文档有点问题，我改一下
