### ISSUE TITLE
按钮点击无响应

### ISSUE THREAD

**Issue by zzicarus** [typora-community-plugin/typora-community-plugin#17]
现在插件中，点击左侧 文件夹/列表 button没有反应，只有通过点击搜索之后再进入才能正确响应
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/118667496/ab938592-7f26-4930-8531-d27053c8551f)

**Comment by plylrnsdy** [comment]
请问有能够稳定复现的步骤吗？没有的话，没那么快搞好😂

**Comment by plylrnsdy** [comment]
哦，懂你意思了

1. 折叠侧栏
2. 点击“文件管理”或“大纲” -> 无法打开侧边栏

**Comment by plylrnsdy** [comment]
请更新到 2.0.13

可以在 左键点击右下角“设置” -> 选择“插件设置” -> “关于”Tab -> 点击“更新”按钮
