### ISSUE TITLE
文件管理中“显示不支持的文件”不生效

### ISSUE THREAD

**Issue by WangChao2021** [typora-community-plugin/typora-community-plugin#18]
希望 Typora 中显示所有的文件，在插件的【外观】【文件管理】中的 “显示不支持的文件” 勾选后，重启Typora，文件列表里还是看不到不支持的文件（word，ppt文件），仍只能看到 md 文件

![Clip_2024-07-03_16-32-03](https://github.com/typora-community-plugin/typora-community-plugin/assets/95513088/d5d69c76-4295-4c96-b8a8-f0540873b5fa)

不知道是不是本身不支持，还是这个功能有bug。

> [!note]  
> **系统**：windows 11 专业版 22h2
> **Typora**：1.9.5
> **插件版本**：2.0.13

**Comment by plylrnsdy** [comment]
应该是 Typora 新版本代码逻辑有变动，需要兼容一下

**Comment by WangChao2021** [comment]
> 应该是 Typora 新版本代码逻辑有变动，需要兼容一下

等大佬的修复 。。。

**Comment by plylrnsdy** [comment]
有点奇怪，有些文件能显示，有些又显示不了

**Comment by WangChao2021** [comment]
> 有点奇怪，文件有时能显示，刷新一下又显示不了

是的，我这边也是这样的，不断重启Typora，偶尔能显示，大多数时候是不显示的

**Comment by plylrnsdy** [comment]
更新到 2.0.14 就好了

**Comment by WangChao2021** [comment]
> 更新到 2.0.14 就好了

更新后就好了

**Comment by plylrnsdy** [comment]
昨晚改出 bug 了，今天才发现拖放文件时会有 bug，请更新到 2.0.15 来修复

**Comment by WangChao2021** [comment]
> 昨晚改出 bug 了，今天才发现拖放文件时会有 bug，请更新到 2.0.15 来修复

好的，辛苦大佬了
