### ISSUE TITLE
安装插件时报错

### ISSUE THREAD

**Issue by JunzheShen** [typora-community-plugin/typora-community-plugin#19]
您好，我在安装插件时报了这个错误
```
Error invoking remote method 'app.download': Error: Cannot find module 'electron-dl' Require stack: - D:\Program Files\Typora\resources\app.asar\atom.js - D:\Program Files\Typora\resources\app.asar\main.node -
```

**Comment by plylrnsdy** [comment]
可以提供一下你的运行环境吗？

- 操作系统及版本
- Typora 版本
- typora-community-plugin 版本
- 安装的插件

**Comment by JunzheShen** [comment]
> 可以提供一下你的运行环境吗？
> 
> * 操作系统及版本
> * Typora 版本
> * typora-community-plugin 版本
> * 安装的插件

您好，操作系统是Windows10，Typora版本是1.9.3，typora-community-plugin 版本是2.0.17，安装的插件是Collapsible Section

**Comment by plylrnsdy** [comment]
现在 Typora 最新版本是 1.9.5，我现在在用这个版本，可以正常安装插件，你更新 Typora 看看

**Comment by JunzheShen** [comment]
> 现在 Typora 最新版本是 1.9.5，我现在在用这个版本，可以正常安装插件，你更新 Typora 看看

更新之后可以了！感谢神医！

**Comment by plylrnsdy** [comment]
我看了下 Typora 更新日志，1.9.4 说修复了下载图片的问题。看了下代码，我下载插件也是用一个接口，所以需要更新到 1.9.4 或以上
