### ISSUE TITLE
incorrect route

### ISSUE THREAD

**Issue by Sergi-Diaz** [typora-community-plugin/typora-community-plugin#2]
Hi, I couldn't get it to work, and it was because this route is misspelled, there is a missing "m" in community in your instructions XD

Wrong:          Copy files to %UserProfile%/.typora/comunity-plugins

Correct:         Copy files to %UserProfile%/.typora/community-plugins

As a detail, I had to create the folder myself, perhaps this step should be notified.

And finally, thank you very much, this is something that was missing in Typora, it's great!

**Comment by plylrnsdy** [comment]
I am glad that it can help you :)

And thanks for your help. I have fixed the README typo now.
