### ISSUE TITLE
doesn't work w/ Typora 1.9.3 on Linux

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-community-plugin#20]
I guess this is no surprise. Is there anything I can do to make it work though?

**Comment by plylrnsdy** [comment]
It work in my computer:

- OS: Ubuntu 22
- Typora: 1.9.3-1
- typora-comunity-plugin: 1.0.19

Can you give more details?
Or you can re-install to try again.

**Comment by thob** [comment]
- OS: Pop!_OS 22.04 LTS
- Typora: 1.9.3
- typora-community-plugin: 2.0.19

plugin files added
![2024-07-25_15-20](https://github.com/user-attachments/assets/b43a492c-be61-4ff4-a680-f038892491e1)

window.html edited
![2024-07-25_15-23](https://github.com/user-attachments/assets/808e8f09-5990-4494-8593-100dab5e2aab)

**Comment by plylrnsdy** [comment]
Looks like the installation is correct. What does Typora look like after launching it?

**Comment by thob** [comment]
Typora's look is unchanged

Here's the console
![2024-07-25_16-24](https://github.com/user-attachments/assets/13483607-0cce-4707-82f3-881480835265)

**Comment by thob** [comment]
All good now. I'll explore it now. Thanx
