### ISSUE TITLE
Support global settings | 支持全局设置

### ISSUE THREAD

**Issue by plylrnsdy** [typora-community-plugin/typora-community-plugin#22]

**Comment by thob** [comment]
being able to use the same settings globally would be helpful. Still, it should be possible to overwrite them w/ vault-based setting. In any case I think it would help if it is explicit that certain settings are applied globally or locally (vault based)

**Comment by plylrnsdy** [comment]
How about this use cases:

- open a folder which hasn't `.typora` will use global settings
  - in settings modal, can click a button to create `.typora` for vault settings
- open a folder which has `.typora` will use vault settings

**Comment by thob** [comment]
Sounds good to me. The UX for creating the .typora file (and deleting) is crucial. Maybe just a checkbox (labeled somehow)

**Comment by plylrnsdy** [comment]
My idea like this:

| using global settings | using vault settings |
|---|---|
| ![](https://github.com/user-attachments/assets/45378088-da7f-419f-b426-e0394a61de5d) | ![](https://github.com/user-attachments/assets/fcc0595e-4b2b-4c5b-b271-4616e495f4ed) |

**Comment by plylrnsdy** [comment]
2.2.2 supported global settings. Usage documentation in [here](https://github.com/typora-community-plugin/typora-community-plugin/blob/main/docs/en-us/user-guide/3-settings.md)

**Comment by thob** [comment]
let me check this over the coming days…

**Comment by plylrnsdy** [comment]
fix a bug in v2.2.3
