### ISSUE TITLE
RFC: Add plugin of note templater | 添加笔记模板插件

### ISSUE THREAD

**Issue by plylrnsdy** [typora-community-plugin/typora-community-plugin#23]
Tasks:
- [x] new quick open panel
- [x] parse template
- [x] template API `tp`

**Comment by thob** [comment]
this would be awesome. In my use case I'd like to use pre-populated templates for several properties, this way I will not overlook it and don't need to memorize where a certain stylesheet or image is located.

**Comment by plylrnsdy** [comment]
Steps of ceate note with templater:

- write `xxx.tmpl.md` in folder `templates`
- use Command Panel run command "Creat note with a template"
- select a template from list
- input the properties in template one by one
- render the template with the properties

Template format:

```markdown
````js
props({
  title: 'string',                  // show a input box
  type: ['book', 'video', 'music'], // show a selector
})
````

# {{type == 'book' ? '📕' : type == 'video' ? '🎞' : '🎵'}} {{title}}
```

**Comment by plylrnsdy** [comment]
**Version 2**

Steps of ceate note with templater:

1. write `xxx.tmpl.md` in folder `templates`
2. open Command Panel and run command "Creat note with a template"
3. show a Command-Panel-liked modal, select a template from list
4. parse template, run the code
   - show Command-Panel-liked modal one by one to request user's inputs
   - set ouput filepath by code
6. render the template with user's inputs
7. if no filepath, show Command-Panel-liked modal for request

Template format:

```markdown
:::
const title = tp.prompt({
  type: 'string',
  label: 'title',
  default: 'Untitled',
})
const type = tp.prompt({
  type: 'select',
  label: 'type',
  options: ['book', 'video', 'music'],
})
:::

# {{type == 'book' ? '📕' : type == 'video' ? '🎞' : '🎵'}} {{title}}
```

PS: here ::: should be ```, github is not support put a codeblock in another

**Comment by thob** [comment]
do you conceive of the templates just for frontmatter for Pandoc purposes?

**Comment by plylrnsdy** [comment]
Do you have a detailed example? I only have a little experience with Pandoc (merging several Markdown files into one and then transforming it to PDF).

**Comment by thob** [comment]
Here's a link to possible variables for Pandoc export https://pandoc.org/chunkedhtml-demo/6.2-variables.html

**Comment by thob** [comment]
this might also be useful https://github.com/OliverBalfour/obsidian-pandoc/issues/56, I'm no expert

**Comment by plylrnsdy** [comment]
Typora supports [Pandoc variables in Front Matter][1] & [Others][2]. I think that it didn't need a plugin.

This plugin only create a markdown from a template.

[1]: https://support.typora.io/YAML/#export
[2]: https://pandoc.org/MANUAL.html#variables

**Comment by thob** [comment]
well, it would be nice to have templates (the frontmatter part) for different use cases which require different variables

**Comment by plylrnsdy** [comment]
you mean using variables in front matter?

```markdown
:::js
const tags = tp.prompt({
  type: 'multi-select',
  label: 'tags',
  options: ['a', 'b', 'c'],
})
:::

---
tags: 
{{tags.map(tag => `- ${tag}`).join('\n')}}
---

# Title
```

PS: here `:::` should be <code>```</code>, github is not support putting a codeblock in another

**Comment by thob** [comment]
Yes, currently I get all the properties I define in Frontmatter. Ideally a template for writing an article contains a different set of properties as for instance a todo list
