### ISSUE TITLE
插件能否支持全局配置

### ISSUE THREAD

**Issue by WangChao2021** [typora-community-plugin/typora-community-plugin#24]
经常需要单独打开位于不同位置的 `md` 文档，目前修改 typora-community-plugin 及相关子插件的设置，默认会在 `md` 文档所有目录生成 `.typora` 目录并保存设置到此目录下，换个位置打开 `md` 文档，又需要重新设置一遍。

能不能将  typora-community-plugin 及相关子插件的设置作为一个全局的设置，打开所有不同位置的 `md` 文档均使用这个已经配置好的全局配置

**Comment by plylrnsdy** [comment]
duplicated with #22
---
和 #22 重复

**Comment by plylrnsdy** [comment]
正在想怎么改，只是配置改动涉及多个地方，不那么好改

**Comment by plylrnsdy** [comment]
你觉得这个UI有没有问题 https://github.com/typora-community-plugin/typora-community-plugin/issues/22#issuecomment-2271368726

**Comment by WangChao2021** [comment]
> 你觉得这个UI有没有问题 [#22 (comment)](https://github.com/typora-community-plugin/typora-community-plugin/issues/22#issuecomment-2271368726)

可以的，我就是想，如果在不使用活动栏的情况下，能不能也能这么设置，我的使用习惯是隐藏活动栏，通过 F1 进入设置的，除了上面的设置入口，F1的命令，也把这几个配置入口加进去就可以了

**Comment by plylrnsdy** [comment]
这里有3个命令：
- 使用全局配置
- 使用本地配置
- 删除本地配置

意思是目录下有 `.typora` 的本地配置也可以不用？那如何判断用不用？

**Comment by WangChao2021** [comment]
> 这里有3个命令：
> 
> * 使用全局配置
> * 创建并使用本地配置
> * 删除本地配置
> 
> 意思是目录下有 `.typora` 的本地配置也可以不用？那如何判断用不用？
> 
> 我本来的想法是：
> 
> * 使用全局配置 → 删除本地配置，切换到全局配置
> * 使用本地配置 → 创建并使用本地配置

目录下的 `.typora` 肯定是要的，不然不好控制本地配置

**Comment by plylrnsdy** [comment]
目前是这样的：

![menu-setting-local](https://github.com/user-attachments/assets/c5c718da-8d8a-4dc0-8907-cc8ad3d7f832)

![commands](https://github.com/user-attachments/assets/9221f50f-82ec-4be5-b3a0-bc344aff7102)

自用测试中，要是没问题周末发

**Comment by plylrnsdy** [comment]
最新版本 v2.2.2 已发布。文档在[这里](https://github.com/typora-community-plugin/typora-community-plugin/blob/main/docs/zh-cn/user-guide/3-settings.md)

**Comment by WangChao2021** [comment]
> 最新版本 v2.2.2 已发布。文档见[这里](https://github.com/typora-community-plugin/typora-community-plugin/blob/main/docs/zh-cn/user-guide/3-settings.md)

全局配置无法持久保存，关掉 Typora 再次打开，又还原了默认配置了

**Comment by plylrnsdy** [comment]
脑子抽了，原本对的，多加了一个条件判断就错了。改回来了

已修复于 v2.2.3

**Comment by WangChao2021** [comment]
> 脑子抽了，原本对的，多加了一个条件判断就错了。改回来了
> 
> 已修复于 v2.2.3

不知道这个算不算问题，默认配置下，点击 “打开命令面板”无反应

**Comment by plylrnsdy** [comment]
貌似不算，这个是用来绑快捷键的，命令面板打开命令面板没有意义。我屏蔽一下

**Comment by WangChao2021** [comment]
> 貌似不算，这个是用来绑快捷键的，命令面板打开命令面板没有意义。我屏蔽一下

最新版本 v2.23 测试下来，全局配置功能正常了
