### ISSUE TITLE
安装 2.1.4 以及 之后的版本无效

### ISSUE THREAD

**Issue by howie6879** [typora-community-plugin/typora-community-plugin#25]
你好，安装 2.1.3 时候正常：

<img width="1133" alt="image" src="https://github.com/user-attachments/assets/c8e111d4-5fb8-4dfa-8907-193796965e6d">

系统&软件版本：

macos 14.1.1 (23B81)
typora：1.9.4

准备升级后续版本操作后都没反应

**Comment by howie6879** [comment]
升级后功能失效

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/50063360-a8df-43cd-98ce-5022c18a6425">

启动后侧边栏也没有

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/4dad12c6-49f9-4633-a31a-5341dd46ae88">

**Comment by howie6879** [comment]
2.1.3 也不是每次都生效，要重启几次

**Comment by plylrnsdy** [comment]
你在 macOS 14 上，2.1.3 之前都是正常使用的，是吗？

**Comment by plylrnsdy** [comment]
我在 macOS 10.13 也出问题了，暂时看不出什么问题，我调试一下

**Comment by howie6879** [comment]
> 我在 macOS 10.13 也出问题了，暂时看不出什么问题，我调试一下

好的 辛苦了

**Comment by plylrnsdy** [comment]
更新到 2.2.6，你看看行不行

**Comment by howie6879** [comment]
@plylrnsdy 可以了，感谢，提个小建议

1.
<img width="808" alt="image" src="https://github.com/user-attachments/assets/abd1f213-4c4e-4c14-8e94-aad7b444767f">
图标可以参考 typora 本身和 vscode 那样，看起来现代化一点

2.多个文件打开 tab 之间切换很卡

作者可以考虑参考下这个项目，能引用就引用，做个插件兼容，利用下这个已有的生态

https://github.com/obgnail/typora_plugin

感谢🫶

**Comment by plylrnsdy** [comment]
1. 我用的是 Typora 自带的 FontAwesome v4，我看看里面还有啥图标
2. 你是不是用了 collapsible-section 插件？我看了下，这个插件目前比较消耗性能，1k 行的文件打开速度会慢 1s，到时候优化下

**Comment by howie6879** [comment]
1.图标可能影响不大，估计是设置的大小比较大？然后边框不用弄那么粗
2.没有用，tab 文件切换要两三秒才会

**Comment by plylrnsdy** [comment]
1. 我试一下调下粗细
2. 你的文件行数多少？你写的都是大文件吗😂

**Comment by plylrnsdy** [comment]
我在 Windows 几十行的文件秒切
在虚拟机里的 macOS 倒是特卡，没办法 macOS 闭源，虚拟机兼容性不好。
你不装这个插件系统是正常的，然后装了之后特别卡？

**Comment by howie6879** [comment]
不装插件系统不是没法开多个 tab 么

**Comment by plylrnsdy** [comment]
这个 Tab 是模拟出来的，相当于在文件树打开不同文件，调的是 Typora 自己的接口

**Comment by howie6879** [comment]
<img width="785" alt="image" src="https://github.com/user-attachments/assets/269235af-5bcb-4d35-a07d-9fb05bc90ac6">
左边切换很快  顶部切换很慢

**Comment by plylrnsdy** [comment]
你的硬盘是机械硬盘？

**Comment by howie6879** [comment]
通过左边切换 console

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/5c2346e1-2861-4fa8-b619-f32eddf3be00">


通过顶部切换，很慢，日志如下

<img width="1311" alt="image" src="https://github.com/user-attachments/assets/4254d143-9441-4ac9-ac22-870865ea728d">


我看不出啥差别

> 你的硬盘是机械硬盘？

我是mbp

**Comment by plylrnsdy** [comment]
有个猜想，你试试这个包 

[typora-community-plugin-2.2.6-beta.1.zip](https://github.com/user-attachments/files/16740459/typora-community-plugin-2.2.6-beta.1.zip)

**Comment by howie6879** [comment]
是这个原因，目前测试没问题了，不过是否存在应该很快吧？

**Comment by plylrnsdy** [comment]
typora 的 macOS 版本和 Windows/Linux 的版本框架不一样
- macOS: Swift + Webview，包体积小，兼容性差
- Windows/Linux: Electron (Node.js + Chromium)，包体积大，兼容性好

所以需要这个插件系统也需要兼容跨平台。

由于无法直接访问 macOS 本地 API（除非改 Swift 相关代码，或者另外加个后台？），使用了等价 API（比较绕，有的是调用终端命令），性能比较差

**Comment by howie6879** [comment]
大概了解，你按照自己思路走，期待后续更新

我将你的项目推荐到我的周刊了，略尽绵薄之力，是个好项目，加油！

https://weekly.howie6879.com/2024/08-19~08-25.%E8%80%81%E8%83%A1%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC156%E6%9C%9F%EF%BC%89.html

**Comment by howie6879** [comment]
@plylrnsdy 作者你好，新的样式很漂亮，但是发现个新问题

![image](https://github.com/user-attachments/assets/f5e92d0d-d700-454f-b890-e8d9ae21ee0f)

一个是 h1标题下 字被 tab 切换遮住了一点点
二十右边侧边滚动条也被挡住了

**Comment by plylrnsdy** [comment]
tab 的样式和这个主题不兼容，你这个主题叫什么？我看看怎样才能兼容不同主题

**Comment by howie6879** [comment]
https://github.com/liangjingkanji/DrakeTyporaTheme 的 drake-google

**Comment by plylrnsdy** [comment]
我在 macOS 10.13 测试的时候，没有这么大的间距。。只有 6px，在 2.2.11 修复了

你这个好奇怪，是不是有自定义的样式

**Comment by howie6879** [comment]
@plylrnsdy 测试没问题了，辛苦，我没自定义样式。

你是不是没有进入软件独占屏幕的模式

**Comment by plylrnsdy** [comment]
换了个实现方式，你再看看 2.2.13

**Comment by howie6879** [comment]
@plylrnsdy 有个样式小问题，我就不开新 issue 了辛苦看下

<img width="745" alt="image" src="https://github.com/user-attachments/assets/e0b25d04-f1e9-4989-b885-27daba89515e">

**Comment by plylrnsdy** [comment]
请更新到 v2.2.21

**Comment by howie6879** [comment]
@plylrnsdy 安装最新版本又出现同样的问题了 安装无效

**Comment by plylrnsdy** [comment]
已修复，请更新 2.3.20

**Comment by howie6879** [comment]
@plylrnsdy 谢谢 已经修复
