### ISSUE TITLE
打开插件配置对话框快捷键修改后，原快捷键依然生效

### ISSUE THREAD

**Issue by morty6688** [typora-community-plugin/typora-community-plugin#27]
![image](https://github.com/user-attachments/assets/a0bb35a5-b056-45e6-8cf0-b2c2dfa0b744)
如图，原始快捷键是（ctrl+.），改成f2之后，按原来的快捷键依然会弹出这个框

typora：1.9.5
插件：2.2.17
win：22631.4037

**Comment by plylrnsdy** [comment]
这个 bug 在 2.2.17 修好了，更新完需要重启 Typora

**Comment by morty6688** [comment]
> 这个 bug 在 2.2.17 修好了，更新完需要重启 Typora

重启typora不行，刚刚重启了系统也不行。。

**Comment by plylrnsdy** [comment]
你看看配置的是全局配置还是本地配置，两个不一样的

**Comment by morty6688** [comment]
> 你看看配置的是全局配置还是本地配置，两个不一样的。
> 
> 旧版只支持本地设置（保存在当前笔记目录下 `.typora`） 新版支持全局设置（保存在安装 core 的目录下的 settings），两个不通用的

好了谢谢~
