### ISSUE TITLE
求助！目前插件提供的功能很有吸引力，就是反复配置，插件无法生效 : (  

### ISSUE THREAD

**Issue by at2008** [typora-community-plugin/typora-community-plugin#29]
目前提供的插件不少是好多typora用户早就期待的功能，比如支持 wikilink 等；今天反复设置了好多次，执行 powershell 脚本、或者手动配置，typora 均毫无反应，typora 开发者模式控制台也没有任何错误提示。

安装过程完全按照文档说明执行的，系统环境：

Windows 10 22H2

Typora 1.9.5

###脚本安装

从 [Release](https://github.com/typora-community-plugin/typora-community-plugin/releases) 下载 typora-community-plugin.zip。
解压文件。
以管理员身份运行 install.ps1 (只适用于 Windows)。
如果你想为自定义安装目录的 Typora 安装它，请以管理员身份运行 install.ps1 -root <TyporaHome>。

### 手动安装

Windows 用户

从 [Release](https://github.com/typora-community-plugin/typora-community-plugin/releases) 下载 typora-community-plugin.zip。
解压文件。
复制文件到 %UserProfile%/.typora/community-plugins。
创建文件夹的符号链接。以管理员身份运行 cmd ，然后运行命令 mklink /d %UserProfile%\\AppData\\Roaming\\Typora\\plugins %UserProfile%\\.typora\\community-plugins。
修改文件 {Typora 安装目录}/resources/window.html。使用 UTF-8 编码（否则会https://github.com/typora-community-plugin/typora-community-plugin/issues/9）打开文件 window.html，替换文件末尾的文本 </body></html> 为 <script src="typora://app/userData/plugins/loader.js" type="module"></script></body></html>。

**Comment by plylrnsdy** [comment]
没有报错吗，我什么都不知道也没办法啊😂

你能用自己的语言描述一下，安装过程有什么异常、或者自己觉得不清楚的地方吗？

**Comment by at2008** [comment]
> 没有报错吗，我什么都不知道也没办法啊😂
> 
> 你能用自己的语言描述一下，安装过程有什么异常、或者自己觉得不清楚的地方吗？

我也郁闷，不知道怎么描述，都是按文档描述步骤反复重复设置，甚至卸载、安装了typora几次，配置后，用 ctrl + . 呼唤不出来 设置界面，查看typora 的 console 日志 也没有任何异常，似乎没有调用插件一样；有什么办法判断或者测试对比，typora是否调用了插件脚本load.js?

**Comment by plylrnsdy** [comment]
你在开发者模式控制台 Elements 选项卡，拉到最下面看看有没有 `<script src="typora://app/userData/plugins/loader.js" type="module"></script>`

**Comment by plylrnsdy** [comment]
活动栏和文件标签栏显示了没有

**Comment by at2008** [comment]
> 你在开发者模式控制台 Elements 选项卡，拉到最下面看看有没有 `<script src="typora://app/userData/plugins/loader.js" type="module"></script>`

似乎是调用了 load.js , 活动栏和文件标签栏 都没有显示 

![image](https://github.com/user-attachments/assets/2b14fdf8-6867-4d8d-890c-c95960f340cc)

**Comment by plylrnsdy** [comment]
提供一下路径：
- Typora 的安装路径
- typora-community-plugin.zip 解压路径

**Comment by at2008** [comment]
> 提供一下路径：
> 
> * Typora 的安装路径
> * typora-community-plugin.zip 解压路径

typora： C:\Program Files\Typora

**Comment by plylrnsdy** [comment]
你看一下有没有这个目录 C:\Users\xxx\AppData\Roaming\Typora\plugins

**Comment by at2008** [comment]
> 你看一下有没有这个目录 C:\Users\xxx\AppData\Roaming\Typora\plugins

有的，执行 `mklink /d %UserProfile%\AppData\Roaming\Typora\plugins %UserProfile%\.typora\community-plugins`  自动创建的

![image](https://github.com/user-attachments/assets/e3f59334-aed7-4f3c-8849-e4ff40420a42)

**Comment by plylrnsdy** [comment]
window.html 你用什么软件改的？

**Comment by at2008** [comment]
> window.html 你用什么软件改的？

notpad3

![image](https://github.com/user-attachments/assets/ae906eef-00a8-4c75-a0f9-0646455424b2)

**Comment by plylrnsdy** [comment]
你看看开发者模式控制台 Sources 选项卡

![](https://github.com/user-attachments/assets/dc4c1ec9-2445-47b3-b05b-aecdef951928)

**Comment by plylrnsdy** [comment]
我到时候看看加个日志和日志开关好了

**Comment by at2008** [comment]
> 你看看开发者模式控制台 Sources 选项卡
> 
> ![](https://private-user-images.githubusercontent.com/18095255/363992713-dc4c1ec9-2445-47b3-b05b-aecdef951928.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzA1MzAsIm5iZiI6MTcyNTM3MDIzMCwicGF0aCI6Ii8xODA5NTI1NS8zNjM5OTI3MTMtZGM0YzFlYzktMjQ0NS00N2IzLWIwNWItYWVjZGVmOTUxOTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEzMzAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ODgyY2VhODZhM2E5NTJjNjliYWY3ZjY0Zjk2ZGU1ODIwZWI1Yjk3MDk5M2ExOTBiNTQ4YzM2MzE0ZGE5MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.830aWFAzwOFglYb0krn_C8vVENyGdPfx4IoysaGScBs)

![image](https://github.com/user-attachments/assets/b50ceb1f-aba7-49ac-8404-4908348aff03)

**Comment by at2008** [comment]
> 我到时候看看加个日志和日志开关好了

期待更新  ❤

**Comment by plylrnsdy** [comment]
临时加了点日志，你试一下这个版本

[typora-community-plugin-v2.3.0-beta.1.zip](https://github.com/user-attachments/files/16849829/typora-community-plugin-v2.3.0-beta.1.zip)

**Comment by at2008** [comment]
> 临时加了点日志，你试一下这个版本
> 
> [typora-community-plugin-v2.3.0-beta.1.zip](https://github.com/user-attachments/files/16849829/typora-community-plugin-v2.3.0-beta.1.zip)
> 
> 然后在 Console 选项卡 Filter 输入框输入 core.js 过滤一下日志

![image](https://github.com/user-attachments/assets/9a0c03d0-bfd3-4704-817c-f045dde3c1c1)

**Comment by at2008** [comment]
> 好的，发现问题了

期待 👍

**Comment by plylrnsdy** [comment]
更新到 2.3.2 就行了

**Comment by at2008** [comment]
> 更新到 2.3.2 就行了

好神奇，终于可以了；折腾了1天，看你们都似乎都没有这个问题，搞得我都不敢随便反映这个问题了 : ) ；

![image](https://github.com/user-attachments/assets/6ba606bd-fee6-4fba-ae61-75de984efee0)

**Comment by plylrnsdy** [comment]
这个问题也是最近更新了全局配置才有的

以前有自己本地配置的老用户发现不了，新用户才会发现😂

**Comment by at2008** [comment]
感谢及时更新代码！ ❤👍
