### ISSUE TITLE
"User" in macOS instructions should be "Users"

### ISSUE THREAD

**Issue by scbarton** [typora-community-plugin/typora-community-plugin#3]
Hi, an important correction for the macOS instructions: "User" in the path to `loader.js` should be "Users". So the correct text to be copied is:

```
<script src="file:///Users/{UserName}/Library/Application%20Support/abnerworks.Typora/plugins/loader.js" type="module"></script></body>
```

**Comment by scbarton** [comment]
Thanks for making this!

**Comment by plylrnsdy** [comment]
I updated the README. Thank you for your help, glad it could assist you :)
