### ISSUE TITLE
文件名包含空格的情况下，wikilink 格式无效，markdown 格式链接无法正常跳转

### ISSUE THREAD

**Issue by at2008** [typora-community-plugin/typora-community-plugin#30]
比如：

`[[测 试#第二章|第二章]]`

wikilink 格式无效

`[第二章](<测 试.md#第二章>)`

markdown 格式链接无法正常跳转

**Comment by plylrnsdy** [comment]
第一个可以啊，我中英文都测试了

第二个确实不行，没兼容尖括号

**Comment by at2008** [comment]
> 第一个可以啊，我中英文都测试了

第一个的确可以，我测试有误

**Comment by plylrnsdy** [comment]
2.3.6 修复了超链接不支持锚点的问题

**Comment by at2008** [comment]
> ~2.3.6 修复了超链接不支持锚点的问题~
> 
> 不支持中文😂，我再看看

不急，慢慢来 😂

**Comment by at2008** [comment]
> ~2.3.6 修复了超链接不支持锚点的问题~
> 
> 不支持中文😂，我再看看

链接用 `(<链接>) ` 这样的方式试试

`[第二章](<测 试.md#第二章>)`

**Comment by plylrnsdy** [comment]
增加了3种情况的支持，更新 core 到 2.3.9 就行了

**Comment by at2008** [comment]
感谢！  ❤ 效率太高了！ 👍

试过了，几种链接都可以正常跳转了！

**Comment by at2008** [comment]
> 增加了3种情况的支持，更新 core 到 2.3.9 就行了

看一下是否需要再完善一下下？如果是链接到另外一个.md 文件，obsidian是支持链接中不带.md后缀的，比如：

`[第二章](测 试.md#第二章)`

`[第二章](测 试#第二章)`

上面两种都可以

目前插件只支持链接中带.md的方式跳转。

**Comment by plylrnsdy** [comment]
Typora 本身不支持，我只能加个配置选项（默认禁用）来支持

**Comment by at2008** [comment]
> Typora 本身不支持，我只能加个配置选项（默认禁用）来支持

好的！

**Comment by plylrnsdy** [comment]
已更新于 2.3.11

**Comment by at2008** [comment]
@plylrnsdy 感谢升级和回复，升级2.3.11版本，连接中带 .md 后缀的，可以跳转；不带 .md 的还是不行；比如：

`[测试AA#第二章](测试AA.md#第二章)`

![image](https://github.com/user-attachments/assets/52087202-984e-465e-a3b4-3edce7239056)

**Comment by plylrnsdy** [comment]
有个新选项需要打开，插件设置 → 文件与链接 → 无后缀 Markdown 超链接

**Comment by at2008** [comment]
@plylrnsdy 感谢及时更新！确实可以了！❤ 😊 👍

**Comment by at2008** [comment]
@plylrnsdy 如果链接不带.md，但是带其他后缀，比如.json，是不是打开链接的时候吧链接自动改成了 xxx.json.md 了？您测试一下是不是。我这测试是这样的。可能需要过滤一下有后缀名的链接。

**Comment by plylrnsdy** [comment]
那就是文件名包含 `.` 就是有后缀，就不加 `.md` 了吧

**Comment by at2008** [comment]
> 那就是文件名包含 `.` 就是有后缀，就不加 `.md` 了吧

可以这样判断。

**Comment by plylrnsdy** [comment]
已更新 2.3.13

**Comment by at2008** [comment]
> 已更新 2.3.13

好了好了！ 非常感谢！ ❤ 😊 👍
