### ISSUE TITLE
如果取消 显示活动栏，会导致 文件文件目录 中不支持的文件也隐藏了

### ISSUE THREAD

**Issue by at2008** [typora-community-plugin/typora-community-plugin#31]
插件版本：2.3.16

选中 **显示不支持的文件**，如果取消 **显示活动栏**(同时会启用自定义面板)，重新启动 typora 后文件文件目录 中不支持的文件也隐藏了。

![image](https://github.com/user-attachments/assets/232c61a2-e35d-4f2a-a045-90d74e892d1d)

**Comment by plylrnsdy** [comment]
更新到 2.3.19 就行了

**Comment by at2008** [comment]
2.3.19 的确可以了 👍 感谢及时更新和回复！❤
