### ISSUE TITLE
Plugin request: footnote indexer

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-community-plugin#35]
Typora is a great editor but for more serious writing you need footnotes, and managing them manually is cumbersome. It would be great to make this Obsidian plugin, [Tidy Footnotes](https://github.com/charliecm/obsidian-tidy-footnotes), available for Typora. I'm sure lots of authors would appreciate it, see [here](https://github.com/typora/typora-issues/issues/2478).

**Comment by plylrnsdy** [comment]
Ok, I will have a try.

**Comment by plylrnsdy** [comment]
[plugin-footnotes][] released! And plugin core need to update to 2.3.22.

[plugin-footnotes]: https://github.com/typora-community-plugin/typora-plugin-footnotes

**Comment by thob** [comment]
Excellent, will give it a try later today!
