### ISSUE TITLE
macOS 打开应用设置按钮报错

### ISSUE THREAD

**Issue by bestlzk** [typora-community-plugin/typora-community-plugin#36]
Typora版本：1.9.4
![1](https://github.com/user-attachments/assets/f6c84d71-d830-4942-ba3a-e804ade71179)
![2](https://github.com/user-attachments/assets/ea192a72-04ce-4db7-84c2-04bf9fabb13f)

**Comment by plylrnsdy** [comment]
出门了，没有苹果虚拟机暂时测不了。

看代码没问题，都是调用typora原生接口，windows下正常。

另外能说一下
- 运行环境：
  - macos版本
  - 有没有安装其他作者的插件
- 其他功能是否正常？

**Comment by bestlzk** [comment]
macos版本：14.4.1
未安装其他插件
其他初始安装后的功能正常

另外发现Codeblock Copy Button插件的一个bug：
* 打开typora后，点击按钮复制代码块无法成功
* 在typora显示的文档里通过ctrl+c复制过一次内容，之后再点击按钮复制代码块可以成功
* 在其他软件中通过ctrl+c复制过一次内容，之后再点击按钮复制代码又无法成功

`alert(i.UserOp.setClipboard)`获取的代码

```javascript
function(e,t,n,r,a){if(File.isMac)!function(e,t,n,r){var o={};i.isDefined(e)&&(o["text/html"]=E(e)[0]),i.isDefined(t)&&(o["text/markhtml"]=t),i.isDefined(n)&&(o["text/plain"]=n),JSBridge.clipboard.writeForMac(o,r)}(e,t,n,r);else if(File.isNode)if(a){if("cut_before"===File._CopyContentFlag||"cut"==a.type&&e){if(!e)return JSBridge.invoke("webContents.copy"),void(File._CopyContentFlag="cut_after");v(File.editor,null,"delSelection"),File._CopyContentFlag=!1}else if("cut_after"===File._CopyContentFlag){File._CopyContentFlag=!1,e=(E(g.clipboard.readHTML())||[])[0];let t=File._CopyContentRange&&editor.selection.buildUndo(File._CopyContentRange),n=v(File.editor,null,"delSelection",!0);if(File._CopyContentRange){if(n){n.undo.unshift(t);let e=v(editor,null,!0,!0);e&&o.append(n,e)}else v(editor,null,!0);File._CopyContentRange=null}editor.undo.register(n)}else if(e&&!File._CopyContentFlag);else{if(!File._CopyContentFlag)return File._CopyContentFlag=!0,void(!e&&JSBridge.invoke("webContents.copy"));!0!==File._CopyContentFlag||null!==e&&void 0!=e||(e=(E(g.clipboard.readHTML()||e)||[])[0]||"")||console.debug("failed to read html from clipboard"),!t&&/^markhtml\|/.exec(File._CopyContentFlag+"")&&(t=File._CopyContentFlag.substring("markhtml|".length)),File._CopyContentFlag=!1}!function(e,t,n,i,r){null!=n?r.clipboardData.setData("text/plain",n):i&&r.clipboardData.setData("text/plain",""),null!=e?r.clipboardData.setData("text/html",e):i&&r.clipboardData.setData("text/html",""),null!=t?r.clipboardData.setData("text/markhtml",t):i&&r.clipboardData.setData("text/markhtml","")}(e,t,n,r,a),a.preventDefault()}else JSBridge.invoke("clipboard.write",JSON.stringify({html:E(e)[0]||n,text:n}),r||!1),t?(File._CopyContentFlag="markhtml|"+t,JSBridge.invoke("webContents.copy")):File._CopyContentFlag=!1}
```

**Comment by plylrnsdy** [comment]
> 发现Codeblock Copy Button插件的一个bug

你看看这个包有没有问题？

[codeblock-copy-button_1.1.0-beta.zip](https://github.com/user-attachments/files/17429642/codeblock-copy-button_1.1.0-beta.zip)

**Comment by bestlzk** [comment]
> > 发现Codeblock Copy Button插件的一个bug
> 
> 你看看这个包有没有问题？
> 
> [codeblock-copy-button_1.1.0-beta.zip](https://github.com/user-attachments/files/17429642/codeblock-copy-button_1.1.0-beta.zip)
> 
> 覆盖 `/Users/{UserName}/Library/Application%20Support/abnerworks.Typora/plugins/plugins/typora-community-plugin.codeblock-copy-button` 下的文件即可

可以了，使用这个包没问题了

**Comment by plylrnsdy** [comment]
> macOS 打开应用设置按钮报错

找到问题了，macOS 下 Typora “打开应用设置”的实现不一样，是没有 `megaMenu` 这个对象的。

我现在没回家，你能帮忙看看在 macOS 如何打开 Typora “应用设置”的吗？

- 如果是通过菜单栏的话，说明是使用 Swift 原生操作的，JS 插件是访问不了的。
- 其他情况，得再看看

**Comment by bestlzk** [comment]
> > macOS 打开应用设置按钮报错
> 
> 找到问题了，macOS 下 Typora “打开应用设置”的实现不一样，是没有 `megaMenu` 这个对象的。
> 
> 我现在没回家，你能帮忙看看在 macOS 如何打开 Typora “应用设置”的吗？
> 
> * 如果是通过菜单栏的话，说明是使用 Swift 原生操作的，JS 插件是访问不了的。
>   
>   * 可能就得屏蔽掉这个菜单项了
> * 其他情况，得再看看

确实是通过菜单栏调用的，

**Comment by bestlzk** [comment]
又发现了一个问题，勾选了显示不支持的文件后没有生效

**Comment by plylrnsdy** [comment]
> 勾选了显示不支持的文件后没有生效

我重新看了下代码，发现 Typora
- 在 Win/Linux 下是获取所有文件，然后使用 JS 过滤，所以可以实现此功能；
- 在 macOS 下调用 Swift 接口获取文件列表（已经是过滤后的），JS 无法介入😂。下次更新时会隐藏该选项

**Comment by bestlzk** [comment]
> * 在 macOS 下调用 Swift 接口获取文件列表（已经是过滤后的），JS 无法介入😂。下次更新时会隐藏该选项

感觉这个功能还是挺有用的，有办法通过NodeJS获取文件列表来覆盖 Swift 接口获取的文件列表来实现这个功能吗

**Comment by plylrnsdy** [comment]
macOS版的 Typora 是使用 Swift + webview 实现的（没有 Node.js），优点是包体积小，缺点是需要额外的兼容。

除非另外写个小服务器，处理这些逻辑。

**Comment by bestlzk** [comment]
> macOS版的 Typora 是使用 Swift + webview 实现的（没有 Node.js），优点是包体积小，缺点是需要额外的兼容。
> 
> 除非另外写个小服务器，处理这些逻辑。

研究了一下，发现确实返回的文件列表里没有其他类型的文件，不过发现了个方法，可以直接执行命令，应该可以执行命令获取文件列表替换掉之前的文件列表，不过解析命令执行的结果感觉可能比较麻烦

```javascript
bridge.callHandler("controller.runCommand", {"args":"ls /tmp"}, function(n) {alert(JSON.stringify(n))})
```

![screenshot-20241021-123403](https://github.com/user-attachments/assets/e97e3c98-4aa2-41a0-9aa4-b1ea9c0a3791)

**Comment by bestlzk** [comment]
另外发现下面的方法可以打开App设置页面

```javascript
bridge.callHandler("setting.showAndHighlight", "image-setting-group")
```

**Comment by plylrnsdy** [comment]
> `bridge.callHandler("controller.runCommand", ...)`

这个接口我用过，延迟太大，在文件标签页里检查文件是否存在延迟 2s（后来去掉了），用在展开文件夹时获取文件列表肯定会一卡一卡地

**Comment by plylrnsdy** [comment]
> `bridge.callHandler("setting.showAndHighlight", "image-setting-group")`

[typora-community-plugin_2.3.31-beta.1.zip](https://github.com/user-attachments/files/17456372/typora-community-plugin_2.3.31-beta.1.zip)

我用了 `bridge.callHandler("setting.showAndHighlight", "files-setting-group")` 看看能不能打开“文件”设置页

**Comment by bestlzk** [comment]
> > `bridge.callHandler("setting.showAndHighlight", "image-setting-group")`
> 
> [typora-community-plugin_2.3.31-beta.1.zip](https://github.com/user-attachments/files/17456372/typora-community-plugin_2.3.31-beta.1.zip)
> 
> 这个版本用了 `bridge.callHandler("setting.showAndHighlight", "files-setting-group")` 看看能不能打开“文件”设置页

可以打开设置页面了，但是只能打开图像设置页，我试过无论第二个参数是什么，都会打开图像设置页，感觉这样也可以了

**Comment by plylrnsdy** [comment]
> 可以打开设置页面了，但是只能打开图像设置页，我试过无论第二个参数是什么，都会打开图像设置页，感觉这样也可以了

已发布在 2.3.32
