### ISSUE TITLE
I can't get `typora-plugin-code-folding` to work

### ISSUE THREAD

**Issue by ziraqyoung** [typora-community-plugin/typora-community-plugin#37]
I have a number of plugins I installed but for some reason this is the only one that doesn't  seem to work (and have never worked for me atleast). I have tried disabling all the other except it with no success.

Spec:
- OS: Pop!_OS 22.04 LTS
 - Typora: 1.9.3
    typora-community-plugin: 2.3.32

---

Devtools output:

 ![image](https://github.com/user-attachments/assets/d74138bb-ad66-4349-a4ec-f2c78fe7a150)

---

Others:

![image](https://github.com/user-attachments/assets/8a44a5d5-40f9-4c1c-a6dc-41d25d978906)

**Comment by plylrnsdy** [comment]
I found the problem, but I am not at home and can not test it without linux vm. Try this:

[code-folding_1.0.1-beta.zip](https://github.com/user-attachments/files/17509658/code-folding_1.0.1-beta.zip)

**Comment by ziraqyoung** [comment]
@plylrnsdy , seems to work  for other languages ( Rust, Go, JS etc) but not Ruby .

![image](https://github.com/user-attachments/assets/2d0a5d86-7502-4bc5-9651-de718a558246)

**Comment by plylrnsdy** [comment]
The reason is that Typora's internal codemirror's modes is not up to date.

I patch it in plugin-code-folding's v1.0.2.

You can update it in "Plugin Settings" modal → "Installed Plugins" → "Check for Update" button → click Code Folding's "Update" button.

**Comment by ziraqyoung** [comment]
Thanks! :+1:  I can live with that
