### ISSUE TITLE
代码块无法选择语言

### ISSUE THREAD

**Issue by lijian12345** [typora-community-plugin/typora-community-plugin#4]
安装插件之后，无法选择代码块的语言，不管是用鼠标点还是回车键都没反应，如下图所示：

![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/26590220/bb967fc6-b711-475c-b178-7833b73a9c72)

BTW，怎么禁用插件呢，方便测试一下禁用之前是什么情况。我记得是可以选择语言的

**Comment by plylrnsdy** [comment]
我这里是可以的，方便说一下你的运行环境吗？
- 操作系统及版本
- Typora 版本
- typora-community-plugin 版本
- 安装的插件

Ctrl+句号 可以打开配置对话框
- “已安装插件”里面可以启用、禁用插件
- 语言可以在“关于”里面选

**Comment by lijian12345** [comment]
> 我这里是可以的，方便说一下你的运行环境吗？
> 
> * 操作系统及版本
> * Typora 版本
> * typora-community-plugin 版本
> * 安装的插件
> 
> Ctrl+句号 可以打开配置对话框
> 
> * “已安装插件”里面可以启用、禁用插件
> * 语言可以在“关于”里面选

你好，相关环境如下：

- 操作系统及版本：23H2(22631.3007)
- Typora 版本：1.7.6
-  typora-community-plugin 版本：2.0.0-beta.33
- 安装的插件：目前只安装了一个copy button

**Comment by plylrnsdy** [comment]
我现在用 Typora 1.6，没装最新版的 Typora，我会测试一下 1.7

卸载载插件系统，根据安装教程反向操作即可。
如果只是想临时禁用插件系统，可以把入口文件 loader.js 改个名字（如：loader.js.bak），找不到 loader.js 就无法加载插件系统

**Comment by plylrnsdy** [comment]
已修复，请更新 typora-community-plugin 到最新版本 2.0.0-beta.34

**Comment by lijian12345** [comment]
> 已修复，请更新 typora-community-plugin 到最新版本 2.0.0-beta.34

好的谢谢~
