### ISSUE TITLE
Can't install Plugin System on Windows

### ISSUE THREAD

**Issue by puffinjr** [typora-community-plugin/typora-community-plugin#40]
Hi, I would love some assistance on how to install the community plugin system for Typora on Windows:

I followed these steps, but ended up with no change to my Typora interface. No ribbon or anything:

1. I opened PowerShell and executed "install.ps1." It seems to have worked given that certain files/folders were created, as seen in the image below
2. Then, I opened Typora but, again, there weren't any visible changes to my interface, no "Settings" Model, no "Plugin Markeplace," nothing

All this to say, any help would be appreciated

![community-plugins](https://github.com/user-attachments/assets/903d8ba5-42b8-4773-a196-59d757592e41)

Here's the log:

![{614007FA-6B54-4252-A2EE-233BCFDF38B3}](https://github.com/user-attachments/assets/a7d4dd91-7389-469f-9d05-610f3e384280)

**Comment by plylrnsdy** [comment]
why `core.js` and `core.css` are in `.typora/community-plugins`?

It should be: 

```
╰─ .typora/community-plugins/
  ├─ 2.3.32/
  │  ├─ locales/
  │  ├─ core.css
  │  ╰─ core.js
  ├─ install.ps1
  ├─ loader.js
  ╰─ loader.json
```

**Comment by puffinjr** [comment]
Ahh, this was the issue! I've got it working now. I don't think the PowerShell script created the folder "2.3.32" to place the core files in. Thanks for the help
