### ISSUE TITLE
是否支持最新版typora1.8.9

### ISSUE THREAD

**Issue by WMD001** [typora-community-plugin/typora-community-plugin#7]
typora 版本 1.8.9
windows11

使用脚本安装后，打开typora无法使用快捷键进入设置界面，是否支持最新版typora

**Comment by plylrnsdy** [comment]
我用 Typora 1.8.10 是可以的。应该是没有安装成功

请问是否使用了管理员权限安装（因为在默认安装位置 C:\Program Files，修改文件需要管理员权限）？

你也可以参考 README 手动安装

**Comment by WMD001** [comment]
重新安装了一下，可以了，另外想问一下，如果想要开发插件的话，有详细的插件开发文档吗？

**Comment by plylrnsdy** [comment]
还没呢，没人看懒得写……

这几天我写个初版

**Comment by WMD001** [comment]
感谢，辛苦大佬了

**Comment by plylrnsdy** [comment]
[中文开发文档](https://github.com/typora-community-plugin/typora-community-plugin/blob/main/docs/zh-cn/dev-guide/1-getting-started.md)

写了一半，先看着吧

**Comment by WMD001** [comment]
👍 大佬辛苦了

**Comment by Explorer-cc** [comment]
你好，请问我win10按照脚本的方式安装到自定义目录并没有报错，通过ctrl+.和F1命令都未生效
但我检查了一下，手动安装的所有内容（包括文件的复制，连接的建立，html末尾文件的替换均正常），但是typora界面就是无法弹出插件的设置，请问这种情况我要如何重新安装呢？总不能手动进行安装的反操作吧
本人的版本是最新的1.8.10正式版   非常感谢大佬

**Comment by Explorer-cc** [comment]
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/78270350/626dbb6c-e96f-4567-bbbb-18100631c66e) 救命，我的vscode突然变成这样了，就在运行了install.ps1之后

**Comment by plylrnsdy** [comment]
> 同时想请问一下能否让插件在typora的主面板上出现某按钮，这样能更好的检查安装是否成功，谢谢大神的付出~

安装成功后，会默认显示 Ribbon 栏和文件标签栏，想要隐藏需要自行在设置页关闭。

**Comment by plylrnsdy** [comment]
> 你好，请问我win10按照脚本的方式安装到自定义目录并没有报错，通过ctrl+.和F1命令都未生效 但我检查了一下，手动安装的所有内容（包括文件的复制，连接的建立，html末尾文件的替换均正常），但是typora界面就是无法弹出插件的设置，请问这种情况我要如何重新安装呢？总不能手动进行安装的反操作吧 本人的版本是最新的1.8.10正式版 非常感谢大佬

请说一下你安装的“自定义目录”是哪里？

**Comment by plylrnsdy** [comment]
> 你好，请问我win10按照脚本的方式安装到自定义目录并没有报错，通过ctrl+.和F1命令都未生效 但我检查了一下，手动安装的所有内容（包括文件的复制，连接的建立，html末尾文件的替换均正常），但是typora界面就是无法弹出插件的设置，请问这种情况我要如何重新安装呢？总不能手动进行安装的反操作吧 本人的版本是最新的1.8.10正式版 非常感谢大佬

有没有可能是快捷键冲突？

**Comment by plylrnsdy** [comment]
> 救命，我的vscode突然变成这样了，就在运行了install.ps1之后

请说一下你安装的“自定义目录”路径、VSCode 安装位置？

**Comment by Explorer-cc** [comment]
> > 你好，请问我win10按照脚本的方式安装到自定义目录并没有报错，通过ctrl+.和F1命令都未生效 但我检查了一下，手动安装的所有内容（包括文件的复制，连接的建立，html末尾文件的替换均正常），但是typora界面就是无法弹出插件的设置，请问这种情况我要如何重新安装呢？总不能手动进行安装的反操作吧 本人的版本是最新的1.8.10正式版 非常感谢大佬
> 
> 有没有可能是快捷键冲突？可以在设置页中修改快捷键

你好，我昨天以管理员身份运行powershell，因为我把install.ps1文件放在了桌面的E盘   因此我先cd路径到解压的typora-community-plugin文件夹，之后运行 install.ps1 -root <TyporaHome>  没有出现报错
我检查了一下，我目前确实是没有快捷键冲突出现的，因此我想试着重装一下这个插件，不知道要如何undo那个mklink

**Comment by Explorer-cc** [comment]
> > 救命，我的vscode突然变成这样了，就在运行了install.ps1之后
> 
> 请说一下你安装的“自定义目录”路径、VSCode 安装位置？
昨天运行的命令行是，切换到install.ps1所在目录后 执行   install.ps1 -root  "D:\Program Files\Typora"

Typora目录地址   "D:\Program Files\Typora"
VScode安装地址   “D:\Program Files\Microsoft VS Code”

**Comment by Explorer-cc** [comment]
> > 救命，我的vscode突然变成这样了，就在运行了install.ps1之后
> 
> 请说一下你安装的“自定义目录”路径、VSCode 安装位置？
昨天运行的命令行是，切换到install.ps1所在目录后 执行   install.ps1 -root  "D:\Program Files\Typora"

Typora目录地址   "D:\Program Files\Typora"
VScode安装地址   “D:\Program Files\Microsoft VS Code”

**Comment by Explorer-cc** [comment]
此外我发现在一体化模式下我的typora也变成了这样，完全无法进行设置
感觉是两者的UI代码被破坏了，也许是调用的同一个文件损坏了
由于本人的VSCODE作为主力软件，现在不想重新配置，希望能提供帮助，不胜感谢！
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/78270350/310c7699-08d3-4703-843b-3b7247e02a31)

**Comment by Explorer-cc** [comment]
![image](https://github.com/typora-community-plugin/typora-community-plugin/assets/78270350/0dff93db-0157-4d47-b4e0-3ddf5dd4cfe5)
昨天具体执行的命令如上图

**Comment by Explorer-cc** [comment]
我现在的想法是，想要在尽量不重装的前提下尽快恢复VScode
斗胆发一个q ： 804318655，因为确实也比较着急，想提高一下沟通效率，有偿，提前感谢作者大大~
